CREATE TABLE inventory_items(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    bl5 INT,
    bl6 INT,
    bl7 INT,
    bl9 INT,
    sp5 INT,
    sp6 INT,
    sp7 INT,
    sp9 INT,
    wl5 INT,
    wl6 INT,
    wl7 INT,
    wl9 INT,
    ld8 INT,
    ld9 INT,
    ld11 INT,
    dld INT,
    pp INT,
    cups50 INT,
    cups60 INT,
    cups80 INT,
    cups100 INT,
    cups150 INT,
    cups210 INT,
    cups250 INT,
    bd5 INT,
    bd6 INT,
    bd7 INT,
    cp5 INT,
    cp6 INT,
    cp7 INT,
    cp9 INT
);
CREATE TABLE inventory (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    bl5_unit VARCHAR(10),
    bl6_unit VARCHAR(10),
    bl7_unit VARCHAR(10),
    bl9_unit VARCHAR(10),
    sp5_unit VARCHAR(10),
    sp6_unit VARCHAR(10),
    sp7_unit VARCHAR(10),
    sp9_unit VARCHAR(10),
    wl5_unit VARCHAR(10),	
    wl6_unit VARCHAR(10),	
    wl7_unit VARCHAR(10),	
    wl9_unit VARCHAR(10),
    ld8_unit VARCHAR(10),	
    ld9_unit VARCHAR(10),	
    ld11_unit VARCHAR(10),	
    dld_unit VARCHAR(10),
    pp_unit VARCHAR(10),
    cups50_unit VARCHAR(10),
    cups60_unit VARCHAR(10),
    cups80_unit VARCHAR(10),
    cups100_unit VARCHAR(10),
    cups150_unit VARCHAR(10),
    cups210_unit VARCHAR(10),
    cups250_unit VARCHAR(10),
    bd5_unit VARCHAR(10),
    bd6_unit VARCHAR(10),
    bd7_unit VARCHAR(10),
    cp5_unit VARCHAR(10),
    cp6_unit VARCHAR(10),
    cp7_unit VARCHAR(10),
    cp9_unit VARCHAR(10)
);
