CREATE TABLE inventory_items(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    bl5 INT,
    bl6 INT,
    bl7 INT,
    bl9 INT,
    sp5 INT,
    sp6 INT,
    sp7 INT,
    sp9 INT,
    wl5 INT,
    wl6 INT,
    wl7 INT,
    wl9 INT,
    ld8 INT,
    ld9 INT,
    ld11 INT,
    dld INT,
    pp INT,
    cups50 INT,
    cups60 INT,
    cups80 INT,
    cups100 INT,
    cups150 INT,
    cups210 INT,
    cups250 INT,
    bd5 INT,
    bd6 INT,
    bd7 INT,
    cp5 INT,
    cp6 INT,
    cp7 INT,
    cp9 INT
);
CREATE TABLE inventory (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    bl5_value INT,
    bl6_value INT,
    bl7_value INT,
    bl9_value INT,
    bl5_unit VARCHAR(10),
    bl6_unit VARCHAR(10),
    bl7_unit VARCHAR(10),
    bl9_unit VARCHAR(10),
    sp5_value INT,
    sp6_value INT,
    sp7_value INT,
    sp9_value INT,
    sp5_unit VARCHAR(10),
    sp6_unit VARCHAR(10),
    sp7_unit VARCHAR(10),
    sp9_unit VARCHAR(10),
    -- Add similar columns for other items and their units
    cups50_value INT,
    cups60_value INT,
    cups80_value INT,
    cups100_value INT,
    cups150_value INT,
    cups210_value INT,
    cups250_value INT,
    cups50_unit VARCHAR(10),
    cups60_unit VARCHAR(10),
    cups80_unit VARCHAR(10),
    cups100_unit VARCHAR(10),
    cups150_unit VARCHAR(10),
    cups210_unit VARCHAR(10),
    cups250_unit VARCHAR(10),
    bd5_value INT,
    bd6_value INT,
    bd7_value INT,
    bd5_unit VARCHAR(10),
    bd6_unit VARCHAR(10),
    bd7_unit VARCHAR(10),
    cp5_value INT,
    cp6_value INT,
    cp7_value INT,
    cp9_value INT,
    cp5_unit VARCHAR(10),
    cp6_unit VARCHAR(10),
    cp7_unit VARCHAR(10),
    cp9_unit VARCHAR(10)
);
